name: Lagrange.Core NuGet Push

on:
  push:
    branches:
        - 'master'
    paths:
        - '/Lagrange.Core/**'
        - '/Lagrange.Core.sln'
        - '/LICENSE'
        - '/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Pack
        run: dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg Lagrange.Core

      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source --username Linwenxuan05 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LagrangeDev/index.json"

      - name: Push generated package to GitHub registry
        run: dotnet nuget push .\Lagrange.Core\bin\Release\*.nupkg --source "github" --api-key ${{ secrets.GIT_TOKEN }}

      - name: Push generated package to NuGet
        run: dotnet nuget push .\Lagrange.Core\bin\Release\*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }}
